### ISSUE TITLE
What's the difference between Extract and Export?

### ISSUE THREAD

**Issue by Videogamer555** [iAmAsval/FModel#113]
When I right click on an asset I can choose to "export" or "extract" it. What's the difference?

**Comment by iAmAsval** [comment]
Export will export the raw data
Extract will get the raw data and read it in memory

**Comment by Videogamer555** [comment]
Is there some kind of "convert all" function, that will scan all the pak files, and convert every game asset it discovers to a commonly used equivalent file format (if one exists, and ignore the asset if no commonly used file format exists)?
For example, extract all MP4 video files, and for any videos that are not already MP4 format (such as those using a proprietary Fortnite video format), convert those to MP4 and output this converted MP4.
Same with all sounds and images.

**Comment by iAmAsval** [comment]
well, first of all, nobody puts mp4 videos in 2020 games because it's not worth the space they take when you can simply stream them.
second, it's not recommended nor build for that kind of job but you can already do this
1. press `F6` to auto save images
2. extract the root folder
3. wait
this is gonna check all files, save textures, generated images, and audios (uncheck `auto open sounds` in the settings) and that's all

**Comment by Videogamer555** [comment]
Of the many JSON formated files in these paks, I found several that included references to MP4 files, but I couldn't find the MP4 files that were referenced. If they aren't in the pak files, then where are they?

**Comment by FabianFG** [comment]
On your game files folder under /Movies/

**Comment by FabianFG** [comment]
And no files are json formatted, that's just the way the are exported

**Comment by Videogamer555** [comment]
What do you mean my "game files" folder? You mean C:\Program Files\Epic Games\Fortnite?

**Comment by FabianFG** [comment]
Yes
