### ISSUE TITLE
Convenient way to bulk-convert and export compressed audio

### ISSUE THREAD

**Issue by Saalvage** [iAmAsval/FModel#236]
### Description

The current best way to achieve exporting compressed (wwise .wem in particular) audio in non-compressed form seems to be adding all of it to the audio player, skipping through each track so it gets converted to .wav and then saving the playlist. However, especially for big batches this can be incredibly time consuming and annoying.

**Comment by iAmAsval** [comment]
FModel is not an audio converter and will never be one
if your game use compressed audio files and you want them all, make a script

https://github.com/iAmAsval/FModel/blob/master/FModel/ViewModels/AudioPlayerViewModel.cs#L558-L580

**Comment by Saalvage** [comment]
Then why bother supporting the feature half-assedly? I can't imagine it'd be that hard to make `savePlaylist` behave properly with encrypted files. I've already hacked together what I need. I'm only bothering to ask because FModel is the only tool that was able to do UE4 decryption followed by proper .wem conversion that I found lol.

**Comment by iAmAsval** [comment]
it is not half of a feature, it is an extra one added for quickly listening to compressed adpcm files not bulk converting 14k wem files that don't even come with names by default

if that was a feature, we would use an actual C# audio parser and converter that supports a lot of audio format, including the wem variants, which today, doesn't exist.

That's why we have to use vgmstream's demo executable to do so, and in my opinion, spam calling another exe's command in a software like FModel is stealing someone else's work to make the user feel like you did the hard work
