### ISSUE TITLE
Exporting failure

### ISSUE THREAD

**Issue by ZHYPE** [iAmAsval/FModel#38]
When i try to export everything is working until i get to this gray texture and then it says error by the way i was exporting all paks

**Comment by iAmAsval** [comment]
can you be more descriptive, please
what's the name of this gray texture
what are you trying to do exactly

**Comment by MyNameIsDark01** [comment]
I think because You can't export all files in the paks

**Comment by iAmAsval** [comment]
technically you can but that's not made for this

**Comment by ZHYPE** [comment]
when i click "load" then "load all packs" then when i right click on "Fortnitegame" and click "extract folder and subfolders I get error with code saying "Cannot access Child value on newtonsoft.json.linq.jvalue" and th code is "null"

**Comment by MyNameIsDark01** [comment]
It should give an error and crash

**Comment by ZHYPE** [comment]
but it does not give an error and im on the newest version

**Comment by ZHYPE** [comment]
and the name is "F_MED_Nautilus_FaceAcc.uasset"

**Comment by MyNameIsDark01** [comment]
what is the file that stop the exporting?

**Comment by ZHYPE** [comment]
the one i just said was the last one successfully exported but it shows nothing else after that

**Comment by iAmAsval** [comment]
it fails because meshes and animations aren't supported and by exporting the FortniteGame folder you're looping on all files including meshes and animations
I don't get the goal of extracting literally everything but QuickBMS with the unreal_tournament_4 script is made for this, you can get it [here](https://zenhax.com/viewtopic.php?f=9&t=1005&start=220)

**Comment by ZHYPE** [comment]
ok thank you could you maybe add support at a later time
